TOKEN=3096735a55cd468878745e424c323c3afdee180cce15e58fea5d7928f6e0605c
3SCALE_URL=3scale-admin.apps.cluster-a1a6.a1a6.sandbox1817.opentlc.com
IMAGE_ADDRESS=registry.access.redhat.com/3scale-amp20/apicast-gateway:1.0
APICAST_CONFIGURATION_CACHE=0
THREESCALE_DEPLOYMENT_ENV=staging
APICAST_CONFIGURATION_LOADER=lazy
APICAST_LOG_LEVEL=debug
THREESCALE_CONFIG_FILE=config.json

docker run --rm -p 8080:8080 \
    -v $(pwd)/policy:/opt/app/policies/jwt-token-introspection-policy/1.0 \
    -e THREESCALE_CONFIG_FILE=config.json
    -e APICAST_CONFIGURATION_CACHE=$APICAST_CONFIGURATION_CACHE \
    -e THREESCALE_DEPLOYMENT_ENV=$THREESCALE_DEPLOYMENT_ENV \
    -e APICAST_CONFIGURATION_LOADER=$APICAST_CONFIGURATION_LOADER \
    -e APICAST_LOG_LEVEL=$APICAST_LOG_LEVEL \
    -e THREESCALE_PORTAL_ENDPOINT=https://$TOKEN@$3SCALE_URL $IMAGE_ADDRESS