apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: my-gateway
spec:
  adminPortalCredentialsRef:
    name: 3scaleportal
  cacheConfigurationSeconds: 0
  configurationLoadMode: lazy
  responseCodesIncluded: true
  logLevel: info
  oidcLogLevel: info
  extendedMetrics: true
  deploymentEnvironment: staging
  exposedHost:
    host: api-3scale-apicast-gateway.apps.cluster-b851.b851.sandbox243.opentlc.com
    tls:
    - {}
  customPolicies:
    - name: JWE Introspection Policy
      version: "0.1"
      secretRef:
        name: jwe-token-introspection