apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: my-gateway
spec:
  adminPortalCredentialsRef:
    name: 3scaleportal
  cacheConfigurationSeconds: 0
  configurationLoadMode: lazy
  responseCodesIncluded: true
  logLevel: info
  oidcLogLevel: info
  extendedMetrics: true
  deploymentEnvironment: staging
  exposedHost:
    host: apicast-bb-labs.apps.wkshop.rhbr-lab.com
    tls:
    - {}
  customPolicies:
    - name: "JWE Introspection Policy with Header Mods"
      version: "0.1"
      secretRef:
        name: jwe-token-introspection